package:
  name: "pyqint"
  version: "0.9.5.2"

source:
  path: .

requirements:
  build:
    - numpy
    - python {{ python }}

  host:
    - pip
    - python
    - setuptools
    - cython
    - numpy

  run:
    - python
    - numpy

test:
  requires:
    - numpy >=1.17
    - setuptools
    - nose
  source_files:
    - tests/*.py
    - tests/results/*.npy

about:
  home: https://github.com/ifilot/pyqint
  license: GPL3
  license_family: GPL
  summary: Python package for evaluating integrals of Gaussian type orbitals in electronic structure calculations
  description: See the package README.md for more information.
