package:
  name: "pyqint"
  version: "0.9.4.0"

source:
  path: .

build:
  include_recipe: False

requirements:
  build:
    - numpy >=1.21
    - python {{ python }}

  host:
    - pip
    - python
    - setuptools
    - cython
    - numpy >=1.21

  run:
    - python
    - numpy >=1.21

test:
  requires:
    - numpy >=1.21
    - setuptools
    - nose >=1.3.7
  source_files:
    - tests/*.py
    - tests/results/*.npy

about:
  home: https://github.com/ifilot/pyqint
  license: GPL3
  license_family: GPL
  summary: Python package for evaluating integrals of Gaussian type orbitals in electronic structure calculations
  description: See the package README.md for more information.
