package:
  name: "pyqint"
  version: "0.7.2.1"

source:
  path: .

requirements:
  build:
    - numpy
    - tqdm

  host:
    - pip
    - python
    - setuptools
    - cython
    - numpy
    - tqdm

  run:
    - python
    - numpy
    - tqdm

test:
  requires:
    - numpy
    - setuptools
    - tqdm
    - nose
  source_files:
    - tests/*.py
    - tests/results/*.npy
  commands:
    - nosetests tests

about:
  home: https://github.com/ifilot/pyqint
  license: GPL3
  license_family: GPL
  summary: Python package for evaluating integrals of Gaussian type orbitals in electronic structure calculations
  description: See the package README.md for more information.
