package:
  name: "pyqint"
  version: "0.12.0.0"

source:
  path: .

requirements:
  build:
    - numpy
    - scipy
    - python {{ python }}

  host:
    - pip
    - python
    - setuptools
    - cython
    - numpy
    - scipy

  run:
    - python
    - numpy
    - scipy

test:
  requires:
    - numpy
    - scipy
    - setuptools
    - nose
  source_files:
    - tests/*.py
    - tests/results/*.npy
    - tests/results/*.txt
  commands:
    - nosetests tests

about:
  home: https://github.com/ifilot/pyqint
  license: GPL3
  license_family: GPL
  summary: Python package for evaluating integrals of Gaussian type orbitals in electronic structure calculations
  description: See the package README.md for more information.
