package:
  name: "pyqint"
  version: "1.1.1"

source:
  path: .

requirements:
  build:
    - numpy
    - scipy
    - python {{ python }}

  host:
    - pip
    - python
    - setuptools
    - cython
    - numpy
    - scipy

  run:
    - python
    - numpy
    - scipy
    - tqdm

test:
  requires:
    - numpy
    - scipy
    - setuptools
    - pytest
  source_files:
    - tests/*.py
    - tests/results/*.npy
    - tests/results/*.txt
    - tests/results/*.xyz
  commands:
    - pytest

about:
  home: https://github.com/ifilot/pyqint
  license: GPL3
  license_family: GPL
  summary: An Educational Hartree-Fock Code in Python: Transparent Implementation of Gaussian-Type Integrals, SCF Procedures, and Geometry Optimization.
  description: See the package README.md for more information.