name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
#-------------------------------------------------------------------------------
# PyPI / Linux
#-------------------------------------------------------------------------------
  build-pypi-linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - name: Install dependencies
      run: |
        yum -y install libgomp mlocate gcc
        /opt/python/cp37-cp37m/bin/python -m pip install numpy scipy tqdm cython pytest
        /opt/python/cp38-cp38/bin/python -m pip install numpy scipy tqdm cython pytest
        /opt/python/cp39-cp39/bin/python -m pip install numpy scipy tqdm cython pytest
        /opt/python/cp310-cp310/bin/python -m pip install numpy scipy tqdm cython pytest
        /opt/python/cp311-cp311/bin/python -m pip install numpy scipy tqdm cython pytest
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build
      run: ./deploy/docker_setup_github.sh
    - name: Test
      run: ./deploy/docker_test_github.sh
    - name: Archive wheels
      uses: actions/upload-artifact@v3
      with:
        name: pypi-linux-wheels
        path: wheelhouse/pyqint-*.whl
#-------------------------------------------------------------------------------
# Anaconda / Windows
#-------------------------------------------------------------------------------
  build-anaconda-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set-up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Set-up MSVC toolchain
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Build
        shell: bash -l {0}
        run: |
          echo $PATH
          conda build . --no-include-recipe
      - name: Archive packages
        uses: actions/upload-artifact@v3
        with:
          name: anaconda-windows-packages
          path: C:\Miniconda\envs\test\conda-bld\win-64\pyqint-*.tar.bz2
#-------------------------------------------------------------------------------
# Anaconda / Linux
#-------------------------------------------------------------------------------
  build-anaconda-linux:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y build-essential
        - name: Set-up miniconda
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: test
            environment-file: environment.yml
            python-version: 3.8
            auto-activate-base: false
        - name: Build
          run: |
            conda install conda-build
            conda build . --no-include-recipe
        - name: Archive packages
          uses: actions/upload-artifact@v3
          with:
            name: anaconda-linux-packages
            path: /usr/share/miniconda/conda-bld/linux-64/pyqint-*.tar.bz2
#-------------------------------------------------------------------------------
# Anaconda / MacOSx
#-------------------------------------------------------------------------------
  build-anaconda-macos:
      runs-on: macos-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
        - name: Set-up miniconda
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: test
            environment-file: environment.yml
            python-version: 3.8
            auto-activate-base: false
        - name: Build
          run: |
            conda install conda-build
            conda build . --no-include-recipe
        - name: Archive packages
          uses: actions/upload-artifact@v3
          with:
            name: anaconda-macos-packages
            path: /usr/local/miniconda/conda-bld/osx-64/pyqint-*.tar.bz2
